### ISSUE TITLE
Broken numbers in labels

### ISSUE THREAD

**Issue by filipggg** [bprzybylski/amuthesis#2]
Chapter/section numbers are broken when `\ref` and `\label` are used. See https://github.com/filipggg/amuthesis/tree/broken-refs for the demonstration (I modified the `thesis.tex` file).

The problem is with handling `\label` - the entry in .aux is broken, looks like this:

```
\newlabel{chapSource}{{}{9}{}{section*.9}{}}
```
whereas it should like this:

```
\newlabel{chapSource}{{2}{9}{}{section*.9}{}}
```

**Comment by bprzybylski** [comment]
Labels and references to chapters/sections/subsections should now work correctly.
